import { 
  Room, Tenant, Bill, Expense, Complaint, KostSettings, Property, 
  Booking, WebsiteConfig, OperationTask, StaffMember 
} from './types';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    name: 'Green House Kemang',
    type: 'Coliving',
    slug: 'green-house-kemang',
    subdomain: 'greenhousekemang',
    customDomain: 'greenhousekemang.com',
    activeTemplate: 'align',
    address: 'Jl. Kemang Timur No. 42, Mampang Prapatan, Jakarta Selatan',
    city: 'Jakarta Selatan',
    description: 'Boutique coliving & private living di jantung Kemang. Kamar privat fully-furnished dengan ruang komunal estetik, dapur bersama chef-grade, high-speed WiFi, dan suasana asri.',
    coverImage: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&auto=format&fit=crop&q=80',
    facilities: ['WiFi 200 Mbps', 'Private Bathroom', 'AC Inverter', 'Workspace Ergonomis', 'Housekeeping Mingguan', 'Communal Kitchen & Lounge', 'Smart Doorlock', 'Parkir Mobil & Motor'],
    whatsapp: '081298765432',
    ownerName: 'Hendra Wijaya',
    startPriceDay: 280000,
    startPriceMonth: 4550000,
    checkInTime: '14:00',
    checkOutTime: '12:00',
  },
  {
    id: 'prop-2',
    name: 'Align Canggu Sanctuary',
    type: 'Villa',
    slug: 'align-canggu',
    subdomain: 'aligncanggu',
    activeTemplate: 'serene',
    address: 'Jl. Pantai Batu Bolong No. 88, Canggu, Kuta Utara, Badung, Bali',
    city: 'Bali',
    description: 'Sanctuary hunian tropis berkonsep ketenangan dan keasrian alam di Canggu. Dikelilingi taman tropis rimbun, kolam renang alami, dan yoga shala.',
    coverImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200&auto=format&fit=crop&q=80',
    facilities: ['Private Plunge Pool', 'High-Speed Fiber WiFi', 'Daily Cleaning', 'Kitchenette Pribadi', 'King Size Bed', 'Garden View', 'Quiet Coworking Corner'],
    whatsapp: '081377889900',
    ownerName: 'Hendra Wijaya',
    startPriceDay: 650000,
    startPriceMonth: 8500000,
    checkInTime: '14:00',
    checkOutTime: '11:00',
  },
  {
    id: 'prop-3',
    name: 'Urban Kost Dago',
    type: 'Kost',
    slug: 'urban-kost-dago',
    subdomain: 'urbankostdago',
    activeTemplate: 'urban',
    address: 'Jl. Dago Asri No. 15, Coblong, Kota Bandung',
    city: 'Bandung',
    description: 'Kost modern, fungsional, dan tertata rapi untuk mahasiswa ITB/UNPAD & pekerja kreatif. Desain minimalis Jepang, sirkulasi udara sejuk Dago.',
    coverImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&auto=format&fit=crop&q=80',
    facilities: ['AC', 'Kamar Mandi Dalam', 'WiFi 100 Mbps', 'Meja Belajar Luas', 'Dapur Bersama', 'Rooftop Lounge', 'CCTV 24 Jam', 'Kartu Akses RFID'],
    whatsapp: '081122334455',
    ownerName: 'Hendra Wijaya',
    startPriceDay: 190000,
    startPriceMonth: 2800000,
    checkInTime: '13:00',
    checkOutTime: '12:00',
  }
];

export const INITIAL_SETTINGS: KostSettings = {
  kostName: "Green House Kemang",
  address: "Jl. Kemang Timur No. 42, Jakarta Selatan",
  ownerName: "Hendra Wijaya",
  whatsapp: "081298765432",
  checkInTime: "14:00",
  checkOutTime: "12:00",
  bankAccounts: [
    { id: 'bca-1', bankName: 'BCA', accountNumber: '8830918239', accountHolder: 'Hendra Wijaya' },
    { id: 'mandiri-1', bankName: 'Mandiri', accountNumber: '137001928374', accountHolder: 'Green House Living PT' }
  ],
  defaultDueDateDay: 5,
  reminderTemplate: "Halo {nama}, pengingat sewa {kamar} di {nama_kost} jatuh tempo tanggal {tanggal}. Total tagihan: Rp {jumlah}. Mohon lakukan pembayaran melalui rekening resmi kami. Terima kasih!",
  dailyWelcomeTemplate: "Selamat datang di {nama_kost}! Kamar Anda adalah {kamar}. Password WiFi: kemangliving2026. Selamat beristirahat!",
  dailyCheckoutTemplate: "Halo {nama}, terima kasih telah menginap di {nama_kost}. Mohon infokan jika Anda sudah bersiap check-out.",
  autoWhatsAppReminder: true,
  qrisMerchantId: "NMID-12003892718",
  enableMultiKost: true
};

export const INITIAL_ROOMS: Room[] = [
  // Green House Kemang (prop-1)
  {
    id: 'room-101',
    propertyId: 'prop-1',
    number: 'Studio Plus A101',
    status: 'Terisi',
    housekeepingStatus: 'Bersih',
    type: 'Studio Plus',
    price: 4550000,
    pricePerMonth: 4550000,
    pricePerDay: 280000,
    floor: 1,
    size: '4x5 m',
    facilities: ['Private Bathroom', 'AC Inverter', 'Workspace', 'Queen Bed', 'Jendela Hadap Taman', 'Smart TV'],
    maxGuests: 2,
    images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=80'],
    description: 'Kamar lantai 1 dengan akses langsung ke selasar taman dalam, meja kerja luas, dan kamar mandi marmer pribadi.'
  },
  {
    id: 'room-102',
    propertyId: 'prop-1',
    number: 'Studio A102',
    status: 'Kosong',
    housekeepingStatus: 'Bersih',
    type: 'Studio',
    price: 3900000,
    pricePerMonth: 3900000,
    pricePerDay: 250000,
    floor: 1,
    size: '3.5x4.5 m',
    facilities: ['Private Bathroom', 'AC Inverter', 'Workspace', 'Queen Bed', 'Lemari Built-in'],
    maxGuests: 2,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80'],
    description: 'Kamar nyaman dan tenang, ideal untuk profesional muda atau digital nomad.'
  },
  {
    id: 'room-103',
    propertyId: 'prop-1',
    number: 'Studio Plus A103',
    status: 'Booking',
    housekeepingStatus: 'Bersih',
    type: 'Studio Plus',
    price: 4550000,
    pricePerMonth: 4550000,
    pricePerDay: 280000,
    floor: 1,
    size: '4x5 m',
    facilities: ['Private Bathroom', 'AC', 'Workspace', 'Queen Bed', 'Balkon Mini'],
    maxGuests: 2,
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80'],
    description: 'Kamar favorit dengan balkon kecil dan pencahayaan matahari pagi yang sangat baik.'
  },
  {
    id: 'room-201',
    propertyId: 'prop-1',
    number: '1 Bedroom Suite B201',
    status: 'Perbaikan',
    housekeepingStatus: 'Kotor',
    type: 'Suite',
    price: 6200000,
    pricePerMonth: 6200000,
    pricePerDay: 380000,
    floor: 2,
    size: '6x5 m',
    facilities: ['Living Area Terpisah', 'Kitchenette', 'Ensuite Bathub', 'King Bed', 'AC 2 Unit', 'Balkon Sunset'],
    maxGuests: 2,
    images: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&auto=format&fit=crop&q=80'],
    description: 'Suite eksklusif lantai 2 dengan ruang santai pribadi, saat ini dalam pemeliharaan rutin AC.'
  },
  {
    id: 'room-202',
    propertyId: 'prop-1',
    number: 'Studio B202',
    status: 'Kosong',
    housekeepingStatus: 'Bersih',
    type: 'Studio',
    price: 3900000,
    pricePerMonth: 3900000,
    pricePerDay: 250000,
    floor: 2,
    size: '3.5x4.5 m',
    facilities: ['Private Bathroom', 'AC Inverter', 'Meja Kerja', 'Queen Bed'],
    maxGuests: 2,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&auto=format&fit=crop&q=80'],
    description: 'Unit lantai dua menghadap pepohonan rimbun, suasana sangat tenang.'
  },
  {
    id: 'room-203',
    propertyId: 'prop-1',
    number: 'Studio Plus B203',
    status: 'Terisi',
    housekeepingStatus: 'Bersih',
    type: 'Studio Plus',
    price: 4550000,
    pricePerMonth: 4550000,
    floor: 2,
    size: '4x5 m',
    facilities: ['Private Bathroom', 'AC', 'Workspace', 'Queen Bed'],
    maxGuests: 2,
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80'],
    description: 'Studio lapang lantai 2 dengan ventilasi silang.'
  },

  // Align Canggu (prop-2)
  {
    id: 'room-c01',
    propertyId: 'prop-2',
    number: 'Garden Villa V01',
    status: 'Terisi',
    housekeepingStatus: 'Bersih',
    type: 'Villa 2BR',
    price: 8500000,
    pricePerMonth: 8500000,
    pricePerDay: 650000,
    floor: 1,
    size: '8x8 m',
    facilities: ['Plunge Pool', 'Open Air Bathroom', 'Outdoor Kitchen', 'King Bed', 'Tropical Garden'],
    maxGuests: 3,
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80'],
    description: 'Villa privat bernuansa alami dengan plunge pool dan taman tropis.'
  },
  {
    id: 'room-c02',
    propertyId: 'prop-2',
    number: 'Serene Suite V02',
    status: 'Kosong',
    housekeepingStatus: 'Bersih',
    type: 'Suite',
    price: 6800000,
    pricePerMonth: 6800000,
    pricePerDay: 550000,
    floor: 1,
    size: '6x6 m',
    facilities: ['Private Garden View', 'Workspace', 'Bathtub', 'High Speed Wifi'],
    maxGuests: 2,
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&auto=format&fit=crop&q=80'],
    description: 'Suite tenang untuk staycation dan work-from-Bali.'
  },

  // Urban Kost Dago (prop-3)
  {
    id: 'room-d01',
    propertyId: 'prop-3',
    number: 'Urban Standard 101',
    status: 'Terisi',
    housekeepingStatus: 'Bersih',
    type: 'Standard',
    price: 2800000,
    pricePerMonth: 2800000,
    pricePerDay: 190000,
    floor: 1,
    size: '3x4 m',
    facilities: ['AC', 'WiFi', 'Kamar Mandi Dalam', 'Meja Belajar'],
    maxGuests: 1,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80'],
    description: 'Kamar compact efisien dekat lobby dan pantry.'
  },
  {
    id: 'room-d02',
    propertyId: 'prop-3',
    number: 'Urban Deluxe 201',
    status: 'Kosong',
    housekeepingStatus: 'Bersih',
    type: 'Deluxe',
    price: 3200000,
    pricePerMonth: 3200000,
    pricePerDay: 220000,
    floor: 2,
    size: '3.5x4 m',
    facilities: ['AC', 'WiFi', 'Kamar Mandi Dalam', 'Balkon Kota'],
    maxGuests: 2,
    images: ['https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&auto=format&fit=crop&q=80'],
    description: 'Kamar lantai 2 dengan pemandangan kota Dago.'
  }
];

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-1',
    propertyId: 'prop-1',
    name: 'Dimas Wicaksono',
    phone: '081234567891',
    email: 'dimas.wicak@gmail.com',
    guestType: 'Bulanan',
    idNumber: '3171092837190001',
    roomAssigned: 'Studio Plus A101',
    moveInDate: '2026-01-15',
    checkOutDate: '2026-07-15',
    rentAmount: 4550000,
    deposit: 4550000,
    status: 'Lunas',
    bookingOrigin: 'Online Web',
    emergencyContact: {
      name: 'Ratih Wicaksono',
      relation: 'Istri / Saudara',
      phone: '081298765000'
    },
    notes: 'Product designer di startup fintech. Sangat rapi dan komunikatif.'
  },
  {
    id: 'tenant-2',
    propertyId: 'prop-1',
    name: 'Sarah Amelia',
    phone: '081987654321',
    email: 'sarah.amelia@outlook.com',
    guestType: 'Bulanan',
    idNumber: '3273019827360002',
    roomAssigned: 'Studio Plus B203',
    moveInDate: '2026-02-01',
    checkOutDate: '2026-08-01',
    rentAmount: 4550000,
    deposit: 4550000,
    status: 'Belum Bayar',
    bookingOrigin: 'WhatsApp',
    emergencyContact: {
      name: 'Dr. Amran Santoso',
      relation: 'Orang Tua',
      phone: '081122339900'
    },
    notes: 'Konsultan manajemen. Menginginkan faktur ditagihkan tiap tanggal 5.'
  },
  {
    id: 'tenant-3',
    propertyId: 'prop-2',
    name: 'Oliver Thorne',
    phone: '+61412345678',
    email: 'oliver.thorne@sydney.edu.au',
    guestType: 'Bulanan',
    idNumber: 'PASSPORT-AU-98217',
    roomAssigned: 'Garden Villa V01',
    moveInDate: '2026-02-10',
    checkOutDate: '2026-05-10',
    rentAmount: 8500000,
    deposit: 8500000,
    status: 'Lunas',
    bookingOrigin: 'Online Web',
    emergencyContact: {
      name: 'Clara Thorne',
      relation: 'Sister',
      phone: '+61499887766'
    },
    notes: 'Remote software engineer from Melbourne.'
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'book-1',
    propertyId: 'prop-1',
    roomId: 'room-103',
    roomType: 'Studio Plus',
    roomNumber: 'Studio Plus A103',
    guestName: 'Jessica Anastasia',
    guestPhone: '081700998877',
    guestEmail: 'jessica.a@gmail.com',
    moveInDate: '2026-03-15',
    moveOutDate: '2026-09-15',
    durationMonths: 6,
    guestsCount: 1,
    totalAmount: 27300000,
    depositAmount: 4550000,
    source: 'Website',
    status: 'Confirmed',
    notes: 'Tertarik karena meja kerja luas dan suasana tenang. Telah membayar deposit.',
    createdAt: '2026-03-01'
  },
  {
    id: 'book-2',
    propertyId: 'prop-1',
    roomId: 'room-102',
    roomType: 'Studio',
    roomNumber: 'Studio A102',
    guestName: 'Bagus Pratama',
    guestPhone: '081233445566',
    guestEmail: 'bagus.pratama@tech.co.id',
    moveInDate: '2026-03-20',
    durationMonths: 3,
    guestsCount: 1,
    totalAmount: 11700000,
    depositAmount: 3900000,
    source: 'Website',
    status: 'Pending',
    notes: 'Permintaan booking langsung dari website greenhousekemang.bisniesgo.id',
    createdAt: '2026-03-07'
  },
  {
    id: 'book-3',
    propertyId: 'prop-2',
    roomId: 'room-c02',
    roomType: 'Suite',
    roomNumber: 'Serene Suite V02',
    guestName: 'Nadia Valerie',
    guestPhone: '081822334455',
    guestEmail: 'nadia.valerie@bali.art',
    moveInDate: '2026-04-01',
    durationMonths: 1,
    guestsCount: 2,
    totalAmount: 6800000,
    depositAmount: 2000000,
    source: 'WhatsApp',
    status: 'Inquiry',
    notes: 'Menanyakan ketersediaan parkir mobil & koneksi internet untuk Zoom.',
    createdAt: '2026-03-08'
  }
];

export const INITIAL_BILLS: Bill[] = [
  {
    id: 'bill-1',
    propertyId: 'prop-1',
    tenantId: 'tenant-1',
    tenantName: 'Dimas Wicaksono',
    roomId: 'room-101',
    roomNumber: 'Studio Plus A101',
    rentalType: 'Bulanan',
    stayDuration: 1,
    period: 'Maret 2026',
    dueDate: '2026-03-05',
    rentAmount: 4550000,
    electricityCharge: 0,
    waterCharge: 0,
    additionalFee: 0,
    discount: 0,
    lateFee: 0,
    totalAmount: 4550000,
    paidAmount: 4550000,
    status: 'Lunas',
    paymentMethod: 'Transfer BCA',
    paymentDate: '2026-03-03',
    notes: 'Dibayar tepat waktu via m-BCA.'
  },
  {
    id: 'bill-2',
    propertyId: 'prop-1',
    tenantId: 'tenant-2',
    tenantName: 'Sarah Amelia',
    roomId: 'room-203',
    roomNumber: 'Studio Plus B203',
    rentalType: 'Bulanan',
    stayDuration: 1,
    period: 'Maret 2026',
    dueDate: '2026-03-05',
    rentAmount: 4550000,
    electricityCharge: 250000,
    waterCharge: 0,
    additionalFee: 0,
    discount: 0,
    lateFee: 0,
    totalAmount: 4800000,
    paidAmount: 0,
    status: 'Belum Bayar',
    notes: 'Pengingat WhatsApp otomatis sudah dikirimkan.'
  },
  {
    id: 'bill-3',
    propertyId: 'prop-2',
    tenantId: 'tenant-3',
    tenantName: 'Oliver Thorne',
    roomId: 'room-c01',
    roomNumber: 'Garden Villa V01',
    rentalType: 'Bulanan',
    stayDuration: 1,
    period: 'Maret 2026',
    dueDate: '2026-03-10',
    rentAmount: 8500000,
    electricityCharge: 0,
    waterCharge: 0,
    additionalFee: 500000,
    discount: 0,
    lateFee: 0,
    totalAmount: 9000000,
    paidAmount: 9000000,
    status: 'Lunas',
    paymentMethod: 'Wise International',
    paymentDate: '2026-03-02',
    notes: 'Sewa + laundry service bulanan.'
  }
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    propertyId: 'prop-1',
    category: 'Internet',
    description: 'Biznet Dedicated 200 Mbps Bulan Maret',
    date: '2026-03-01',
    amount: 1250000,
    notes: 'Koneksi utama coliving Kemang'
  },
  {
    id: 'exp-2',
    propertyId: 'prop-1',
    category: 'Kebersihan',
    description: 'Sabun, disinfektan & refill linen commmunal area',
    date: '2026-03-03',
    amount: 650000
  },
  {
    id: 'exp-3',
    propertyId: 'prop-1',
    category: 'Perbaikan',
    description: 'Service & cuci AC rutin 6 kamar',
    date: '2026-03-04',
    amount: 900000
  }
];

export const INITIAL_COMPLAINTS: Complaint[] = [
  {
    id: 'comp-1',
    propertyId: 'prop-1',
    tenantId: 'tenant-1',
    tenantName: 'Dimas Wicaksono',
    roomId: 'room-101',
    roomNumber: 'Studio Plus A101',
    title: 'Gagang shower kamar mandi agak longgar',
    category: 'Kamar mandi',
    status: 'Diproses',
    priority: 'Sedang',
    date: '2026-03-06',
    description: 'Baut penyangga shower terlepas satu sisi, masih bisa dipakai namun goyang.'
  }
];

export const INITIAL_OPERATION_TASKS: OperationTask[] = [
  {
    id: 'task-1',
    propertyId: 'prop-1',
    type: 'Maintenance',
    title: 'AC tidak dingin & perlu tambah freon',
    roomNumber: 'Suite B201',
    priority: 'Tinggi',
    status: 'In Progress',
    assignedTo: 'Budi (Teknisi AC)',
    estimatedCost: 350000,
    notes: 'Jadwal teknisi datang hari ini jam 15:00 WIB.',
    createdAt: '2026-03-07'
  },
  {
    id: 'task-2',
    propertyId: 'prop-1',
    type: 'Cleaning',
    title: 'Deep cleaning & ganti sprei pasca check-out',
    roomNumber: 'Studio A102',
    priority: 'Sedang',
    status: 'Completed',
    assignedTo: 'Siti (Housekeeping)',
    notes: 'Kamar sudah bersih dan wangi, siap untuk calon tamu berikutnya.',
    createdAt: '2026-03-06'
  },
  {
    id: 'task-3',
    propertyId: 'prop-1',
    type: 'Maintenance',
    title: 'Perbaikan engsel pintu balkon',
    roomNumber: 'Studio Plus A103',
    priority: 'Rendah',
    status: 'Open',
    assignedTo: 'Budi (Teknisi)',
    estimatedCost: 75000,
    createdAt: '2026-03-08'
  }
];

export const INITIAL_WEBSITE_CONFIGS: Record<string, WebsiteConfig> = {
  'prop-1': {
    propertyId: 'prop-1',
    templateId: 'sander',
    subdomain: 'greenhousekemang',
    customDomain: 'greenhousekemang.com',
    headline: 'A better place to live in Kemang.',
    subheadline: 'Fully furnished private rooms, thoughtful shared spaces, and everything you need to feel at home in South Jakarta.',
    aboutText: 'Green House Kemang dirancang untuk mereka yang menghargai ketenangan, kenyamanan berstandar tinggi, dan komunitas penghuni yang selaras di tengah dinamika Jakarta.',
    accentColor: '#173B30',
    showAvailabilityWidget: true,
    showReviews: true,
    showFaq: true,
    whatsappDirect: '6281298765432',
    sections: [
      { id: 'hero', name: 'Hero Banner', enabled: true },
      { id: 'availability', name: 'Ketersediaan Kamar Real-time', enabled: true },
      { id: 'rooms', name: 'Daftar Tipe Kamar', enabled: true },
      { id: 'amenities', name: 'Fasilitas & Layanan', enabled: true },
      { id: 'gallery', name: 'Galeri Foto', enabled: true },
      { id: 'location', name: 'Lokasi & Sekitar', enabled: true },
      { id: 'reviews', name: 'Ulasan Penghuni', enabled: true },
      { id: 'faq', name: 'Pertanyaan Umum (FAQ)', enabled: true },
      { id: 'whatsapp', name: 'Tombol Chat WhatsApp', enabled: true },
    ],
    isPublished: true
  },
  'prop-2': {
    propertyId: 'prop-2',
    templateId: 'serene',
    subdomain: 'aligncanggu',
    headline: 'Sanctuary of calm and natural living in Canggu.',
    subheadline: 'Tropical garden villas and thoughtful monthly residences surrounded by Bali greenery.',
    aboutText: 'Align Canggu menghadirkan hunian yang berpadu dengan alam, dirancang bagi profesional dan pencinta ketenangan yang menginginkan keseimbangan hidup dan kerja.',
    accentColor: '#315A49',
    showAvailabilityWidget: true,
    showReviews: true,
    showFaq: true,
    whatsappDirect: '6281377889900',
    sections: [
      { id: 'hero', name: 'Hero Banner', enabled: true },
      { id: 'availability', name: 'Ketersediaan Kamar', enabled: true },
      { id: 'rooms', name: 'Daftar Kamar & Villa', enabled: true },
      { id: 'amenities', name: 'Fasilitas Alami', enabled: true },
      { id: 'gallery', name: 'Galeri Suasana', enabled: true },
      { id: 'location', name: 'Peta & Lokasi', enabled: true },
      { id: 'reviews', name: 'Testimoni', enabled: true },
      { id: 'faq', name: 'FAQ', enabled: true },
      { id: 'whatsapp', name: 'WhatsApp Concierge', enabled: true },
    ],
    isPublished: true
  },
  'prop-3': {
    propertyId: 'prop-3',
    templateId: 'urban',
    subdomain: 'urbankostdago',
    headline: 'Hunian modern, rapi, dan sejuk di Dago Bandung.',
    subheadline: 'Kost eksklusif dekat ITB & pusat kuliner Dago dengan fasilitas lengkap dan operasional terpercaya.',
    aboutText: 'Urban Kost Dago menawarkan kamar nyaman berfasilitas lengkap dengan tata kelola profesional dan keamanan 24 jam.',
    accentColor: '#171A18',
    showAvailabilityWidget: true,
    showReviews: true,
    showFaq: true,
    whatsappDirect: '6281122334455',
    sections: [
      { id: 'hero', name: 'Hero Banner', enabled: true },
      { id: 'availability', name: 'Cek Kamar Kosong', enabled: true },
      { id: 'rooms', name: 'Pilihan Kamar', enabled: true },
      { id: 'amenities', name: 'Fasilitas', enabled: true },
      { id: 'gallery', name: 'Foto Kamar', enabled: true },
      { id: 'location', name: 'Akses Lokasi', enabled: true },
      { id: 'reviews', name: 'Review', enabled: true },
      { id: 'faq', name: 'FAQ', enabled: true },
      { id: 'whatsapp', name: 'Chat Pemilik', enabled: true },
    ],
    isPublished: true
  }
};

export const INITIAL_STAFF: StaffMember[] = [
  { id: 'staff-1', propertyId: 'prop-1', name: 'Hendra Wijaya', role: 'Owner', phone: '081298765432', email: 'hendra@bisniesgo.id', status: 'Active' },
  { id: 'staff-2', propertyId: 'prop-1', name: 'Maya Santoso', role: 'Manager', phone: '081233445577', email: 'maya@greenhousekemang.com', status: 'Active' },
  { id: 'staff-3', propertyId: 'prop-1', name: 'Budi Santoso', role: 'Operations', phone: '081399887766', email: 'budi.ops@greenhousekemang.com', status: 'Active' },
  { id: 'staff-4', propertyId: 'prop-1', name: 'Siti Rohimah', role: 'Housekeeping', phone: '081544332211', email: 'siti@greenhousekemang.com', status: 'Active' },
];
